create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.QUERY_TIMEOUT_WASTE (
	ACCOUNT_ID NUMBER(38,0),
	DEPLOYMENT VARCHAR(50),
	WAREHOUSE_NAME VARCHAR(16777216),
	LOWERBOUNDCREDITSSAVED_PERCENTAGE FLOAT,
	UPPERBOUNDCREDITSSAVED_PERCENTAGE FLOAT,
	TOTAL_SECONDS FLOAT,
	MAX_WH_CREDITS FLOAT,
	WASTED_SECONDS_MAX_CREDITS FLOAT,
	TOTAL_SECONDS_WITH_TIMEOUT_CUT_MAX_CREDITS FLOAT
);
