import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SNOWFLAKE_USER = "jozhang"
SNOWFLAKE_ACCOUNT = "snowhouse"
SNOWFLAKE_ROLE = "FINOPS_VALUE_ADVISORY_RL"
SNOWFLAKE_WAREHOUSE = "FINOPS_WH"

TEMPLATE_SHEET_ID = "1sVDgZnWcD9LM5e8_9ymYplL2izdlbWqgxYucBTc6b2A"
SLIDES_TEMPLATE_ID = "1w6hTxJ1IhqS-55tsGdLXQMPujY6U5fvwP5jzhHs9YNo"
GOOGLE_DRIVE_FOLDER_ID = "0AL1deHMgLaLrUk9PVA"
GOOGLE_CREDENTIALS_FILE = os.path.join(BASE_DIR, "credentials", "snowflake-corp-finops-analysis-0152d8301e98.json")

FOLDER_LINK = f"https://drive.google.com/drive/folders/{GOOGLE_DRIVE_FOLDER_ID}"

SESSION_VARIABLES = [
    "alter session set timezone = 'UTC'",
    f"use ROLE {SNOWFLAKE_ROLE}",
    f"use warehouse {SNOWFLAKE_WAREHOUSE}",
    "SET SCHEMA = 'FINOPS_OUTPUTS.' || $SCHEMA_NAME",
    "SET ACCOUNT_ROCKS_SAVINGS = $SCHEMA || '.ACCOUNT_ROCKS_SAVINGS'",
    "SET SCOPED_ACCOUNTS = $SCHEMA || '.SCOPED_ACCOUNTS'",
    "SET BILLING = $SCHEMA || '.BILLING'",
    "SET UEQ = $SCHEMA || '.UEQ_COMBINED'",
    "SET UEM = $SCHEMA || '.UEM_COMBINED'",
    "SET WAREHOUSE_AGG = $SCHEMA || '.WAREHOUSE_AGG'",
    "SET ACCOUNT_STORAGE_OVERVIEW = $SCHEMA || '.ACCOUNT_STORAGE_OVERVIEW'",
    "SET UNUSED_STORAGE = $SCHEMA || '.UNUSED_ACTIVE_STORAGE'",
    "SET INACTIVE_STORAGE = $SCHEMA || '.INACTIVE_STORAGE_LT'",
    "SET REPEATED_QUERIES = $SCHEMA || '.REPEATED_QUERIES'",
    "SET ROCKS_SUMMARY = $SCHEMA || '.SCOPED_ACCOUNTS_ROCKS_SUMMARY'",
    "SET UEW = $SCHEMA || '.UEW_COMBINED'",
    "SET AUTO_CLUSTER = $SCHEMA || '.AUTO_CLUSTER_ANALYSIS'",
    "SET ATTRIBUTED_QUERIES = $SCHEMA || '.ATTRIBUTED_COST_QUERY_HISTORY_30D'",
    "SET COST_TABLE = $SCHEMA || '.COST_TABLE'",
    "SET CLOUD_SERVICES_ACCOUNT = $SCHEMA || '.CLOUD_SERVICES_ACCOUNT_AGG'",
    "SET CLOUD_SERVICES = $SCHEMA || '.CLOUD_SERVICES_QUERIES'",
]

EXPECTED_TABLES = [
    "SCOPED_ACCOUNTS",
    "BILLING",
    "SFDC_ACCOUNTS",
    "ULT_SFDC_ACCOUNTS",
    "UEQ_COMBINED",
    "UEM_COMBINED",
    "WAREHOUSE_AGG",
    "UEW_COMBINED",
    "ACCOUNT_STORAGE_OVERVIEW",
    "UNUSED_ACTIVE_STORAGE",
    "INACTIVE_STORAGE_LT",
    "REPEATED_QUERIES",
    "ACCOUNT_ROCKS_SAVINGS",
    "SCOPED_ACCOUNTS_ROCKS_SUMMARY",
    "AUTO_CLUSTER_ANALYSIS",
    "CLOUD_SERVICES_ACCOUNT_AGG",
    "CLOUD_SERVICES_QUERIES",
    "ATTRIBUTED_COST_QUERY_HISTORY_30D",
    "COST_TABLE",
]
