ULTIMATE_PARENT_LOOKUP = """
SELECT DISTINCT
    ult.name as ultimate_parent_salesforce_account_name
FROM snowhouse.sales.account acct
LEFT JOIN snowhouse.sales.account ult
    ON acct.ULTIMATE_PARENT_CASE_SAFE_ID_TEXT_C = ult.id
WHERE true
    AND acct.capacity_counter_c > 0
"""

CREATE_SCHEMA_CLONE = "CREATE OR REPLACE TRANSIENT SCHEMA FINOPS_OUTPUTS.{schema} CLONE FINOPS.L3_TEMPLATE WITH MANAGED ACCESS"

CREATE_ULT_SFDC_ACCOUNTS = """
CREATE OR REPLACE TABLE FINOPS_OUTPUTS.{schema}.ULT_SFDC_ACCOUNTS AS
SELECT
    acct.id as salesforce_account_id,
    acct.name as salesforce_account_name,
    acct.ULTIMATE_PARENT_CASE_SAFE_ID_TEXT_C as ultimate_parent_salesforce_account_id,
    ult.name as ultimate_parent_salesforce_account_name
FROM snowhouse.sales.account acct
LEFT JOIN snowhouse.sales.account ult
    ON acct.ULTIMATE_PARENT_CASE_SAFE_ID_TEXT_C = ult.id
WHERE ult.name = '{ult_parent}'
    AND acct.capacity_counter_c > 0
"""

CREATE_SFDC_ACCOUNTS = """
CREATE OR REPLACE TABLE FINOPS_OUTPUTS.{schema}.SFDC_ACCOUNTS AS
SELECT
    map.salesforce_account_id,
    map.salesforce_account_name,
    map.snowflake_account_id,
    map.snowflake_deployment,
    map.snowflake_account_name,
    a.service_level
FROM finance.customer.salesforce_snowflake_mapping map
JOIN FINOPS_OUTPUTS.{schema}.ULT_SFDC_ACCOUNTS u
    ON u.salesforce_account_id = map.salesforce_account_id
JOIN snowhouse_import.prod.ACCOUNT_EXTENDED_PROPERTIES_ETL_V a
    ON map.snowflake_account_id = a.account_id
    AND map.snowflake_deployment = a.deployment
GROUP BY ALL
"""

BILLING_TABLE = """
CREATE OR REPLACE TABLE FINOPS_OUTPUTS.{schema}.BILLING AS (
    SELECT
        YEAR(map.general_date::DATE) || '-Q' || QUARTER(map.general_date::DATE) AS PERIOD,
        DATE_TRUNC('month', map.general_date::DATE) as MONTH,
        map.SALESFORCE_ACCOUNT_ID as SF_ID,
        map.SALESFORCE_ACCOUNT_NAME as SF_NAME,
        map.snowflake_account_id::INT as ACCOUNT_ID,
        map.snowflake_account_name as NAME,
        SNOWFLAKE_ACCOUNT_ALIAS as ALIAS,
        map.snowflake_deployment as DEPLOYMENT,
        map.CLOUD,
        map.CLOUD_PROVIDER_REGION,
        map.SERVICE_LEVEL,
        map.METERED_CURRENCY,
        map.CONTRACT_CURRENCY,
        map.revenue_category,
        CASE
            WHEN revenue_category IN ('Storage','Reader Storage') THEN 'Storage'
            WHEN revenue_category IN ('Reader Compute','Compute') THEN 'Compute'
            ELSE 'Other'
        END AS revenue_group,
        SUM(round(revenue,2)) as REVENUE,
        SUM(round(REVENUE_LOCAL,2)) as REVENUE_LOCAL,
        SUM(WAREHOUSE_CREDITS) as CREDITS,
        SUM(DAILY_STORAGE_TB + READER_STORAGE_TB) as STORAGE_TB,
        SUM(DATA_TRANSFER_TB + READER_DATA_TRANSFER_TB) as TRANSFER_TB,
        DIV0(SUM(sub.price_per_credit*WAREHOUSE_CREDITS),NULLIF(SUM(WAREHOUSE_CREDITS),0)) as price_per_credit,
        DIV0(SUM(sub.overage_price_per_credit*WAREHOUSE_CREDITS),NULLIF(SUM(WAREHOUSE_CREDITS),0)) as credit_list_price,
        DIV0(SUM(sub.storage_pricing*(daily_storage_tb+READER_STORAGE_TB)),NULLIF(SUM(daily_storage_tb+READER_STORAGE_TB),0)) as storage_pricing,
        DIV0(SUM(sub.overage_storage_pricing*(daily_storage_tb+READER_STORAGE_TB)),NULLIF(SUM(daily_storage_tb+READER_STORAGE_TB),0)) as storage_list_price,
        DIV0(SUM(sub.capacity_discount * revenue),SUM(revenue)) as discount
    FROM finance.customer.SNOWFLAKE_ACCOUNT_REVENUE_LONG map
    JOIN FINOPS_OUTPUTS.{schema}.SFDC_ACCOUNTS sa
        ON map.snowflake_account_id = sa.snowflake_account_id
        AND map.snowflake_deployment = sa.snowflake_deployment
    LEFT JOIN FINANCE.CUSTOMER.PRICING_DAILY sub
        ON map.snowflake_account_id = sub.snowflake_account_id
        AND map.snowflake_deployment = sub.snowflake_deployment
        AND map.general_date::DATE = sub.general_date
    WHERE 1 = 1
        AND map.general_date BETWEEN '{start_date}' AND '{end_date}'
        AND coalesce(revenue,0) <> 0
    GROUP BY ALL
    ORDER BY "MONTH" ASC
)
"""

REVENUE_SUMMARY = """
SELECT
    SF_ID,
    SF_NAME,
    ACCOUNT_ID,
    NAME as LOCATOR,
    ALIAS as ACCOUNT_NAME,
    DEPLOYMENT,
    SUM(REVENUE) as TOTAL_REVENUE,
    SUM(CASE WHEN MONTH >= DATEADD('month',-3,DATE_TRUNC('month',CURRENT_DATE)) THEN REVENUE ELSE 0 END) as LAST_3_MONTH_REVENUE
FROM FINOPS_OUTPUTS.{schema}.BILLING
GROUP BY ALL
"""

CREATE_TASK = """
CREATE OR REPLACE TASK FINOPS_OUTPUTS.{schema}.ACCOUNT_REFRESH
    WAREHOUSE = FINOPS_WH
    SCHEDULE = '60 MINUTES'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    AS CALL FINOPS_OUTPUTS.{schema}.ACCOUNT_ORCHESTRATOR('{schema}')
"""

EXECUTE_TASK = "EXECUTE TASK FINOPS_OUTPUTS.{schema}.ACCOUNT_REFRESH"

SUSPEND_TASK = "ALTER TASK FINOPS_OUTPUTS.{schema}.ACCOUNT_REFRESH SUSPEND"

LIST_SCHEMAS = """
SELECT SCHEMA_NAME, CREATED, LAST_ALTERED
FROM FINOPS_OUTPUTS.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME NOT IN ('INFORMATION_SCHEMA', 'PUBLIC')
ORDER BY LAST_ALTERED DESC
"""

LIST_TABLES_IN_SCHEMA = """
SELECT TABLE_NAME, ROW_COUNT, CREATED, LAST_ALTERED
FROM FINOPS_OUTPUTS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = '{schema}'
ORDER BY TABLE_NAME
"""

TASK_HISTORY = """
SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_MESSAGE
FROM TABLE(FINOPS_OUTPUTS.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'ACCOUNT_REFRESH',
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 20,
    ERROR_ONLY => FALSE
))
WHERE SCHEMA_NAME = '{schema}'
ORDER BY SCHEDULED_TIME DESC
"""

USE_CASES_QUERY_0 = """
SELECT *
FROM SALES.SALES_BI.A360_USE_CASES uc
JOIN (SELECT DISTINCT sf_id FROM identifier($SCOPED_ACCOUNTS)) S
    ON uc.account_id = S.sf_id
WHERE 1 = 1
    AND deliverable_stage_name NOT IN (
        '7 - Deployed',
        '8 - Use Case Lost',
        '0 - Not In Pursuit'
    )
    AND (implementation_start_date_c IS NOT NULL AND ACTUAL_GO_LIVE_DATE_C IS NOT NULL)
    AND actual_go_live_date_c >= DATE_TRUNC('month', CURRENT_DATE())
"""

ADJUSTMENTS_QUERY_1 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    LOCATOR,
    ACCOUNT_NAME,
    REVENUE_GROUP,
    ROCK_CATEGORY,
    ROCK,
    LOW_APPLIED_ADJ_PERCENTAGE,
    HIGH_APPLIED_ADJ_PERCENTAGE,
    LOW_ANNUALIZED_CREDIT_SAVINGS,
    HIGH_ANNUALIZED_CREDIT_SAVINGS,
    LOW_ANNUALIZED_TB_SAVINGS,
    HIGH_ANNUALIZED_TB_SAVINGS,
    LOW_ANNUALIZED_DOLLAR_SAVINGS,
    HIGH_ANNUALIZED_DOLLAR_SAVINGS
FROM identifier($ACCOUNT_ROCKS_SAVINGS)
ORDER BY account_name, HIGH_ANNUALIZED_DOLLAR_SAVINGS DESC
"""

SCOPED_ACCOUNTS_QUERY_2 = """
SELECT
    SF_ID,
    SF_NAME,
    ACCOUNT_ID,
    LOCATOR,
    ACCOUNT_NAME,
    DEPLOYMENT,
    WAREHOUSE_ANALYSIS,
    QUERY_ANALYSIS,
    STORAGE_ANALYSIS,
    OTHER_ANALYSIS,
    ROI_ANALYSIS,
    USAGE_CONTEXT_ANALYSIS
FROM identifier($SCOPED_ACCOUNTS)
"""

BILL_QUERY_3 = """
SELECT
    PERIOD,
    MONTH,
    SF_ID,
    SF_NAME,
    ACCOUNT_ID,
    NAME,
    ALIAS,
    DEPLOYMENT,
    CLOUD,
    CLOUD_PROVIDER_REGION,
    SERVICE_LEVEL,
    METERED_CURRENCY,
    CONTRACT_CURRENCY,
    REVENUE_CATEGORY,
    REVENUE_GROUP,
    REVENUE,
    REVENUE_LOCAL,
    CREDITS,
    STORAGE_TB,
    TRANSFER_TB,
    CREDIT_LIST_PRICE,
    STORAGE_LIST_PRICE
FROM identifier($BILLING)
"""

UEQ_QUERY_4 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    ALIAS,
    PERIOD,
    QUARTER_DATE,
    TOTAL_CREDITS,
    TOTAL_JOBS,
    TOTAL_TB_SCANNED,
    TOTAL_EXECUTION_HOURS,
    TOTAL_COMPUTE_CREDITS,
    TOTAL_SERVERLESS_CREDITS,
    TOTAL_ACTIVE_USERS,
    TOTAL_USED_DATABASES,
    TOTAL_USED_SCHEMAS,
    TOTAL_USED_WAREHOUSES,
    CREDITS_PER_THOUSAND_QUERIES,
    CREDITS_PER_TB_SCANNED
FROM identifier($UEQ)
"""

UEM_QUERY_5 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    ALIAS,
    PERIOD,
    MONTH_DATE,
    TOTAL_CREDITS,
    TOTAL_JOBS,
    TOTAL_TB_SCANNED,
    TOTAL_EXECUTION_HOURS,
    TOTAL_COMPUTE_CREDITS,
    TOTAL_SERVERLESS_CREDITS,
    TOTAL_ACTIVE_USERS,
    TOTAL_USED_DATABASES,
    TOTAL_USED_SCHEMAS,
    TOTAL_USED_WAREHOUSES,
    CREDITS_PER_THOUSAND_QUERIES,
    CREDITS_PER_TB_SCANNED
FROM identifier($UEM)
"""

WH_QUERY_6 = """
SELECT
    w.ACCOUNT_ID,
    w.LOCATOR,
    w.ACCOUNT_NAME,
    w.DEPLOYMENT,
    w.MONTH,
    w.WAREHOUSE_ID,
    w.WAREHOUSE_NAME,
    w.AVG_QUERY_CONCURRENCY,
    w.P80_QUERY_CONCURRENCY,
    w.P95_QUERY_CONCURRENCY,
    w.AVG_QUERY_CONCURRENCY_QUEUED_LOAD,
    w.SIZING_DETAILS,
    w.AVG_WH_LOAD,
    w.P80_WH_LOAD,
    w.P95_WH_LOAD,
    w.EXECUTION_HOURS,
    w.BILLABLE_HOURS,
    w.WAREHOUSE_EFFICIENCY,
    w.AVG_UTILIZATION,
    w.P80_UTILIZATION,
    w.P95_UTILIZATION,
    w.AUTO_RESUME,
    w.AUTO_SUSPEND,
    w.INSTANCE_TYPE,
    w.WAREHOUSE_TYPE,
    w.MCW_SCALING_TYPE,
    w.MIN_CLUSTER_COUNT,
    w.MAX_CLUSTER_COUNT,
    w.MAX_CONCURRENCY_LEVEL,
    w.TIMEOUT_HOURS,
    w.QUERY_ACCELERATION_ENABLED,
    w.QUERY_ACCELERATION_MAX_SCALE_FACTOR,
    w.ETL_FLAG,
    w.COMMENT,
    w.CURRENT_SIZE_AT_ANALYSIS_RUNTIME,
    w.CREDITS_XP,
    w.ATTRIBUTED_COMPUTE_CREDITS,
    w.IDLE_CREDITS,
    w.IDLE_PERCENTAGE,
    w.PERC_SHORT_QUERIES,
    w.PERC_SHORT_QUERY_DURATION,
    uew.total_jobs as XP_JOBS,
    uew.total_tb_scanned as TB_SCANNED,
    w.IDLE_CLUSTER_MINUTES_AFTER_60S,
    w.TOTAL_ACTIVE_CLUSTER_MINUTES,
    w.TOTAL_IDLE_CLUSTER_MINUTES,
    w.PERC_IDLE_AFTER_60S,
    w.IDLE_CREDITS_FROM_AUTOSUSPEND,
    w.LOW_QUERY_TIMEOUT_SAVINGS_PERCENTAGE,
    w.HIGH_QUERY_TIMEOUT_SAVINGS_PERCENTAGE,
    w.LOW_SIZING_CREDIT_SAVINGS,
    w.HIGH_SIZING_CREDIT_SAVINGS,
    w.LOW_CONCURRENCY_CREDIT_SAVINGS,
    w.HIGH_CONCURRENCY_CREDIT_SAVINGS,
    w.LOW_TIMEOUT_CREDIT_SAVINGS,
    w.HIGH_TIMEOUT_CREDIT_SAVINGS,
    w.LOW_IDLE_TIME_CREDIT_SAVINGS,
    w.HIGH_IDLE_TIME_CREDIT_SAVINGS
FROM identifier($WAREHOUSE_AGG) w
LEFT JOIN identifier($UEW) uew
    ON w.account_id = uew.account_id
    AND w.deployment = uew.deployment
    AND w.month = uew.month
    AND w.warehouse_name = uew.warehouse_name
WHERE 1 = 1
ORDER BY CREDITS_XP DESC
"""

STORAGE_QUERY_7 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    ACTIVE_TB,
    TIME_TRAVEL_TB,
    FAILSAFE_TB,
    RETAINED_FOR_CLONE_TB,
    INACTIVE_TB,
    TOTAL_STORAGE_TB,
    ACTIVE_PERCENTAGE,
    INACTIVE_PERCENTAGE
FROM identifier($ACCOUNT_STORAGE_OVERVIEW)
"""

UNUSED_ACTIVE_STORAGE_QUERY_8 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    FULL_TABLE_NAME,
    AUTO_CLUSTERING_ON,
    ACTIVE_TB,
    TB as TOTAL_TB,
    RECLUSTER_CREDITS
FROM identifier($UNUSED_STORAGE)
"""

INACTIVE_STORAGE_QUERY_9 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    FULL_TABLE_NAME,
    ACTIVE_SIZE_TB,
    TIME_TRAVEL_TB,
    FAILSAFE_TB,
    CLONE_RETAIN_TB as RETAINED_FOR_CLONE_TB,
    TABLE_SIZE_TB,
    INACTIVE_SIZE_TB,
    CHURN_PCT,
    INACTIVE_STORAGE_PCT,
    DATA_RETENTION_TIME_IN_DAYS
FROM identifier($INACTIVE_STORAGE)
"""

REPEATED_QUERIES_10 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    QUERY_PARAMETERIZED_HASH,
    WEIGHTED_XP,
    AVG_EXEC,
    QUERY_FROM_CACHE,
    NUMQUERIES,
    WEIGHTED_XP_PER_QUERY,
    ERRORED,
    EXAMPLE_ERROR_MESSAGES,
    EXAMPLE_QUERY_SHORTENED,
    EXAMPLE_WAREHOUSE_NAME,
    NUM_WHS_RUN_IN,
    AVG_WH_SERVER_SIZE,
    GB_SPILLED,
    TB_SCANNED,
    NUM_JOB_CREDITS,
    JOB_CREDIT_QUERY_WITH_EXEC,
    QUERIES_WITH_EXEC,
    JOB_CREDITS,
    ACCOUNT_WEIGHTED_XP,
    ALL_WEIGHTED_XP,
    ACCOUNT_JOB_CREDITS,
    ALL_JOB_CREDITS,
    CANCELLED,
    CANCELLED_CREDITS,
    CANCELLED_CREDITS_PERC_OF_TOTAL,
    ERROR_CREDITS_NO_CANCELLATIONS,
    WEIGHTED_XP_ACCOUNT_PERC_OF_TOTAL,
    WEIGHTED_XP_PERC_OF_TOTAL,
    ACCOUNT_JOB_CREDITS_PERC_OF_TOTAL,
    JOB_CREDITS_PERC_OF_TOTAL,
    ANNUALIZED_JOB_CREDITS,
    ANNUALIZED_SAVINGS_20P,
    ANNUALIZED_SAVINGS_30P,
    RUNNING_TOTAL_JOB_CREDIT,
    ERROR_CREDITS,
    ERROR_CREDITS_PERC_OF_TOTAL,
    RUNNING_TOTAL_ERROR_CREDIT,
    ERROR_RATE,
    ERROR_RATE_NO_CANCELATION_BY_CREDITS,
    ANNUALIZED_ERROR_COST,
    ANNUALIZED_ERROR_SAVINGS_20P,
    ANNUALIZED_ERROR_SAVINGS_30P,
    RESULT_CACHED_QUERY_PERCENTAGE,
    POTENTIAL_SAVINGS_FROM_RESULTS_CACHE,
    POTENTIAL_ANNUALIZED_SAVINGS_FROM_RESULTS_CACHE_30P,
    POTENTIAL_ANNUALIZED_SAVINGS_FROM_RESULTS_CACHE_50P,
    ANNUALIZED_NONERROR_JOB_CREDITS,
    ANNUALIZED_NONERROR_SAVINGS_20P,
    ANNUALIZED_NONERROR_SAVINGS_30P,
    JOB_CREDIT_RANK,
    ERROR_CREDIT_RANK,
    RESULTS_CACHE_RANK,
    NONERROR_JOB_CREDIT_RANK
FROM identifier($REPEATED_QUERIES)
WHERE QUERY_PARAMETERIZED_HASH IS NOT NULL
ORDER BY JOB_CREDIT_RANK
"""

AC_QUERY_11 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    GB_RECLUSTERED,
    TABLE_ACTIVE_GB,
    TOTAL_GB_SCANNED,
    TOTAL_RECLUSTER_CREDITS,
    NUM_QUERIES,
    SELECT_QUERIES,
    DML_JOBS,
    PERCENT_RECLUSTERED
FROM identifier($AUTO_CLUSTER)
WHERE 1 = 1
    AND percent_reclustered > 0
"""

AUTO_SUSPEND_QUERY_12 = """
SELECT
    auto_suspend,
    COUNT(DISTINCT account_id || deployment || warehouse_name) as NB_WH,
    ROUND(sum(idle_credits),2) as idle_credits,
    ROUND(sum(idle_credits)/sum(credits_xp),2)*100 as avg_idle_percentage,
    ROUND(sum(idle_credits_from_autosuspend),2) as idle_credits_from_autosuspend,
    round(100 * RATIO_TO_REPORT(COUNT(DISTINCT account_id || deployment || warehouse_name)) OVER (),2) AS percent_NB_WH,
    round(100 * RATIO_TO_REPORT(SUM(credits_xp)) OVER (),2) AS percent_credits_total
FROM identifier($WAREHOUSE_AGG) w
GROUP BY ALL
ORDER BY auto_suspend ASC
"""

CLOUD_SERVICES_QUERY_13 = """
SELECT
    cs.account_id,
    cs.deployment,
    cs.COPY_SELECTIVITY,
    cs.DDL_FREQUENCY,
    cs.CLONE_FREQUENCY,
    cs.SIMPLE_QUERIES,
    cs.INFORMATION_SCHEMA,
    cs.SHOW_FREQUENCY,
    cs.SINGLE_ROW_INSERTS_FREQUENCY,
    cs.HIGH_COMPILATION,
    cs.CS_TO_OPTIMIZE,
    cs.TOTAL_ADDRESSIBLE_CREDITS,
    cs.CLOUD_CREDITS_ELIGIBLE_TO_OPTIMIZE
FROM identifier($CLOUD_SERVICES_ACCOUNT) cs
ORDER BY HIGH_CLOUD_SERVICES_CREDIT_SAVINGS DESC
"""

CLOUD_SERVICES_QUERIES_QUERY_14 = """
SELECT
    c.account_id,
    c.deployment,
    c.warehouse_name,
    c.query_parameterized_hash,
    q_category,
    LEFT(sample_query_text,50) as sample_query_text,
    calls,
    TOTAL_CLOUD_SERVICES_CREDITS,
    PERC_OF_TOTAL_CLOUD_SERVICES
FROM identifier($CLOUD_SERVICES) c
ORDER BY TOTAL_CLOUD_SERVICES_CREDITS DESC
LIMIT 25
"""

ROCKS_QUERY_20 = """
SELECT
    REVENUE_GROUP,
    ROCK_CATEGORY,
    ROCK,
    TOTAL_LOW_ANNUALIZED_CREDIT_SAVINGS,
    TOTAL_HIGH_ANNUALIZED_CREDIT_SAVINGS,
    TOTAL_LOW_ANNUALIZED_TB_SAVINGS,
    TOTAL_HIGH_ANNUALIZED_TB_SAVINGS,
    TOTAL_LOW_ANNUALIZED_DOLLAR_SAVINGS,
    TOTAL_HIGH_ANNUALIZED_DOLLAR_SAVINGS,
    TOTAL_REVENUE,
    TOTAL_CREDITS,
    TOTAL_STORAGE_TB,
    TOTAL_COMPUTE_REVENUE,
    TOTAL_STORAGE_REVENUE,
    TOTAL_OTHER_REVENUE,
    LOW_REVENUE_CATEGORY_PERCENTAGE_SAVINGS,
    HIGH_REVENUE_CATEGORY_PERCENTAGE_SAVINGS
FROM identifier($ROCKS_SUMMARY)
"""

UEW_QUERY_21 = """
SELECT
    ACCOUNT_ID,
    DEPLOYMENT,
    ALIAS,
    PERIOD,
    MONTH,
    WAREHOUSE_NAME,
    TOTAL_CREDITS,
    TOTAL_JOBS,
    TOTAL_TB_SCANNED,
    TOTAL_EXECUTION_HOURS,
    TOTAL_ACTIVE_USERS,
    TOTAL_USED_DATABASES,
    TOTAL_USED_SCHEMAS,
    CREDITS_PER_THOUSAND_QUERIES,
    CREDITS_PER_TB_SCANNED
FROM identifier($UEW)
WHERE 1 = 1
    AND warehouse_name IS NOT NULL
"""

DBA_WH_DETAIL = """
SELECT
    w.WAREHOUSE_NAME,
    w.ACCOUNT_NAME,
    w.DEPLOYMENT,
    w.CURRENT_SIZE_AT_ANALYSIS_RUNTIME,
    w.SIZING_DETAILS,
    w.CREDITS_XP,
    w.AUTO_SUSPEND,
    w.IDLE_CREDITS,
    w.IDLE_PERCENTAGE,
    w.IDLE_CREDITS_FROM_AUTOSUSPEND,
    w.AVG_UTILIZATION,
    w.P80_UTILIZATION,
    w.P95_UTILIZATION,
    w.AVG_QUERY_CONCURRENCY,
    w.P95_QUERY_CONCURRENCY,
    w.MAX_CONCURRENCY_LEVEL,
    w.TIMEOUT_HOURS,
    w.WAREHOUSE_TYPE,
    w.MCW_SCALING_TYPE,
    w.MIN_CLUSTER_COUNT,
    w.MAX_CLUSTER_COUNT,
    w.PERC_SHORT_QUERIES,
    w.LOW_SIZING_CREDIT_SAVINGS,
    w.HIGH_SIZING_CREDIT_SAVINGS,
    w.LOW_CONCURRENCY_CREDIT_SAVINGS,
    w.HIGH_CONCURRENCY_CREDIT_SAVINGS,
    w.LOW_TIMEOUT_CREDIT_SAVINGS,
    w.HIGH_TIMEOUT_CREDIT_SAVINGS,
    w.LOW_IDLE_TIME_CREDIT_SAVINGS,
    w.HIGH_IDLE_TIME_CREDIT_SAVINGS,
    w.BILLABLE_HOURS,
    w.EXECUTION_HOURS,
    w.WAREHOUSE_EFFICIENCY
FROM identifier($WAREHOUSE_AGG) w
WHERE 1 = 1
ORDER BY w.CREDITS_XP DESC
"""

DBA_TOP_QUERIES = """
SELECT
    EXAMPLE_WAREHOUSE_NAME,
    EXAMPLE_QUERY_SHORTENED,
    NUMQUERIES,
    JOB_CREDITS,
    ANNUALIZED_JOB_CREDITS,
    ERROR_RATE,
    RESULT_CACHED_QUERY_PERCENTAGE,
    ANNUALIZED_ERROR_COST,
    POTENTIAL_ANNUALIZED_SAVINGS_FROM_RESULTS_CACHE_30P
FROM identifier($REPEATED_QUERIES)
WHERE QUERY_PARAMETERIZED_HASH IS NOT NULL
ORDER BY JOB_CREDITS DESC
LIMIT 25
"""

DBA_ROCKS_SUMMARY = """
SELECT
    ROCK_CATEGORY,
    ROCK,
    TOTAL_LOW_ANNUALIZED_CREDIT_SAVINGS,
    TOTAL_HIGH_ANNUALIZED_CREDIT_SAVINGS,
    TOTAL_LOW_ANNUALIZED_DOLLAR_SAVINGS,
    TOTAL_HIGH_ANNUALIZED_DOLLAR_SAVINGS
FROM identifier($ROCKS_SUMMARY)
ORDER BY TOTAL_HIGH_ANNUALIZED_DOLLAR_SAVINGS DESC
"""

QUERY_TO_WORKSHEET = [
    ("USE_CASES_QUERY_0", "0 - Use Cases"),
    ("ADJUSTMENTS_QUERY_1", "1 - Adjustments"),
    ("SCOPED_ACCOUNTS_QUERY_2", "2-Scoped_Accounts"),
    ("BILL_QUERY_3", "3-BILL"),
    ("UEQ_QUERY_4", "4-UEQ"),
    ("UEM_QUERY_5", "5-UEM"),
    ("WH_QUERY_6", "6-WH"),
    ("STORAGE_QUERY_7", "7-ST_T"),
    ("UNUSED_ACTIVE_STORAGE_QUERY_8", "8-ST_A"),
    ("INACTIVE_STORAGE_QUERY_9", "9-ST_I"),
    ("REPEATED_QUERIES_10", "10-Repeated Queries"),
    ("AC_QUERY_11", "11-AC"),
    ("AUTO_SUSPEND_QUERY_12", "12-Auto_Suspend"),
    ("CLOUD_SERVICES_QUERY_13", "13-CloudServices"),
    ("CLOUD_SERVICES_QUERIES_QUERY_14", "14-Cloud Services Queries"),
    ("ROCKS_QUERY_20", "20-ROCKS"),
    ("UEW_QUERY_21", "21-UEW"),
]
