create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.ACCESS_HISTORY (
	ACCOUNT_ID NUMBER(38,0),
	DEPLOYMENT VARCHAR(50),
	TABLE_NAME VARCHAR(16777216),
	ACCESS_TYPE VARCHAR(15),
	NUMBER_OF_ACCESSES NUMBER(18,0)
);
