create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.COST_TABLE (
	SALESFORCE_ACCOUNT_ID VARCHAR(16777216),
	SALESFORCE_ACCOUNT_NAME VARCHAR(16777216),
	ACCOUNT_ID NUMBER(38,0),
	DEPLOYMENT VARCHAR(16777216),
	STORAGE_PRICING_MIN FLOAT,
	STORAGE_PRICING_MAX FLOAT,
	PRICE_PER_CREDIT_MIN FLOAT,
	PRICE_PER_CREDIT_MAX FLOAT,
	STORAGE_PRICE FLOAT,
	PRICE_PER_CREDIT FLOAT
);
