create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.UEQ (
	PERIOD VARCHAR(16777216),
	ACCOUNT_ID NUMBER(38,0),
	DEPLOYMENT VARCHAR(50),
	XP_JOBS NUMBER(13,0),
	DUR_XP_EXECUTING FLOAT,
	CPU_HOURS FLOAT,
	AVG_CONCURRENCY NUMBER(38,6),
	TOTAL_DURATION NUMBER(38,0),
	PRODUCED_ROWS FLOAT,
	BYTES_SPILLED FLOAT,
	BYTES_WRITTEN NUMBER(38,0),
	BYTES_SCANNED FLOAT,
	ACTIVE_USERS NUMBER(18,0),
	USED_DATABASE NUMBER(18,0),
	USED_SCHEMA NUMBER(18,0),
	USED_WAREHOUSE NUMBER(18,0)
);
