create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.WAREHOUSE_UTILIZATION (
	ACCOUNT_ID NUMBER(38,0),
	DEPLOYMENT VARCHAR(16777216),
	WAREHOUSE_ID NUMBER(38,0),
	AVG FLOAT,
	P80 FLOAT,
	P95 FLOAT
);
