create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.WAREHOUSE_IDLE_TIME (
	ACCOUNT_ID NUMBER(38,0),
	DEPLOYMENT VARCHAR(50),
	WAREHOUSE_ID NUMBER(38,0),
	MONTH_DATE TIMESTAMP_NTZ(9),
	IDLE_CLOCK_MINUTES NUMBER(13,0),
	IDLE_CLOCK_MINUTES_AFTER_60S NUMBER(13,0),
	IDLE_CLUSTER_MINUTES_AFTER_60S NUMBER(25,0),
	ACTIVE_CLOCK_MINUTES NUMBER(18,0),
	TOTAL_IDLE_CLUSTER_MINUTES NUMBER(25,0),
	TOTAL_ACTIVE_CLUSTER_MINUTES NUMBER(30,0)
);
