create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.WAREHOUSE_SCORING (
	ACCOUNT_ID NUMBER(38,0),
	ACCOUNT_NAME VARCHAR(16777216),
	DEPLOYMENT VARCHAR(50),
	WAREHOUSE_NAME VARCHAR(16777216),
	WAREHOUSE_ID NUMBER(38,0),
	SIZING_DETAILS VARIANT,
	BILLABLE_HOURS FLOAT,
	EXECUTION_HOURS FLOAT,
	TOTAL_CREDITS FLOAT,
	TOTAL_LOW_OPTIMIZED_CREDITS FLOAT,
	TOTAL_HIGH_OPTIMIZED_CREDITS FLOAT,
	WEIGHTED_P80_WH_LOAD FLOAT,
	WEIGHTED_P95_WH_LOAD FLOAT,
	WEIGHTED_AVG_WH_LOAD FLOAT,
	ESTIMATED_LOW_CREDIT_SAVINGS FLOAT,
	ESTIMATED_HIGH_CREDIT_SAVINGS FLOAT
);
