create or replace TRANSIENT TABLE FINOPS.L3_TEMPLATE.WAREHOUSE_LOAD_HISTORY (
	MONTH DATE,
	ACCOUNT_ID NUMBER(38,0),
	DEPLOYMENT VARCHAR(50),
	WAREHOUSE_ID NUMBER(38,0),
	WAREHOUSE_NAME VARCHAR(16777216),
	AVG_RUNNING NUMBER(38,12),
	P80 FLOAT,
	P95 FLOAT,
	AVG_QUEUED_LOAD NUMBER(38,12)
);
